preload = ~/Pictures/wallpapers/111645550_p0.png
preload = ~/Pictures/wallpapers/116861314_p0.jpg

wallpaper = eDP-1,~/Pictures/wallpapers/116861314_p0.jpg
wallpaper = HDMI-A-1,~/Pictures/wallpapers/111645550_p0.png

splash = true

